<?xml version="1.0"?>
<package format="3">
  <name>autonomy</name>
  <version>0.1.0</version>
  <description>Local cone perception, planning, and control for FSDS.</description>

  <maintainer email="satvara@example.com">satvara</maintainer>
  <license>GPL-2.0-only</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>nlohmann_json</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>visualization_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>fs_msgs</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>slam</exec_depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
