#!/usr/bin/env zsh

set -e

script_path="${0:A}"
if [[ ! -f /run/.containerenv && ! -f /.dockerenv ]]; then
  exec distrobox enter --no-tty kart-ros2-humble -- "$script_path" "$@"
fi

workspace_root="${script_path:h:h}"
dataset="${1:-$workspace_root/generated/behavior_cloning/datasets}"
exec python3 "$workspace_root/src/behavior_cloning/training/validate_dataset.py" "$dataset"
