#!/usr/bin/env zsh

set -e

script_path="${0:A}"
if [[ ! -f /run/.containerenv && ! -f /.dockerenv ]]; then
  exec distrobox enter --no-tty kart-ros2-humble -- "$script_path" "$@"
fi

workspace_root="${script_path:h:h}"
model_directory="${1:-$workspace_root/generated/behavior_cloning/models/rgbd}"
unset COLCON_CURRENT_PREFIX COLCON_PREFIX_PATH AMENT_PREFIX_PATH CMAKE_PREFIX_PATH
source /opt/ros/humble/setup.zsh
source "$workspace_root/install/setup.zsh"
exec ros2 launch behavior_cloning inference.launch.xml \
  model_path:="$model_directory/model.onnx" \
  metadata_path:="$model_directory/model.json" \
  command_topic:=/behavior_cloning/predicted_command \
  enabled:=true hold_brake_when_disabled:=false
