#!/usr/bin/env zsh

set -e

script_path="${0:A}"
if [[ ! -f /run/.containerenv && ! -f /.dockerenv ]]; then
  exec distrobox enter --no-tty kart-ros2-humble -- "$script_path" "$@"
fi

workspace_root="${script_path:h:h}"
unset COLCON_CURRENT_PREFIX COLCON_PREFIX_PATH AMENT_PREFIX_PATH CMAKE_PREFIX_PATH
source /opt/ros/humble/setup.zsh
source "$workspace_root/install/setup.zsh"
exec ros2 service call /behavior_cloning/enable std_srvs/srv/SetBool '{data: true}'
