#!/usr/bin/env zsh

set -e

script_path="${0:A}"
if [[ ! -f /run/.containerenv && ! -f /.dockerenv ]]; then
  exec distrobox enter kart-ros2-humble -- "$script_path" "$@"
fi

workspace_root="${script_path:h:h}"
source /opt/ros/humble/setup.zsh
source "$workspace_root/install/setup.zsh"

exec ros2 launch single_test sensors.launch.xml "$@"
