#!/usr/bin/env zsh

set -e

script_path="${0:A}"
if [[ ! -f /run/.containerenv && ! -f /.dockerenv ]]; then
  exec distrobox enter kart-ros2-humble -- "$script_path" "$@"
fi

workspace_root="${script_path:h:h}"
source /opt/ros/humble/setup.zsh
source "$workspace_root/install/setup.zsh"

manifest="${1:-$workspace_root/generated/single_test/manifest.json}"
results="${2:-$workspace_root/results}"

exec ros2 run single_test single_test_session --ros-args \
  -p manifest_path:="$manifest" \
  -p results_directory:="$results"
