<?xml version="1.0"?>
<package format="3">
  <name>slam</name>
  <version>0.1.0</version>
  <description>LiDAR SLAM Toolbox mapping and localization pipelines for FSDS.</description>

  <maintainer email="satvara@example.com">satvara</maintainer>
  <license>GPL-2.0-only</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>fs_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>nlohmann_json</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>pointcloud_to_laserscan</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>vio</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
